Repository hyperledger/composer, pull requests merged in 2018-05, with the labels that each got.

#3964 More robust sed match if order changes
  packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md
Labels: docs

#3979 Disable Google Analytics
  .travis/deploy.sh
  packages/composer-website/jekylldocs/_config.yml
  packages/composer-website/jekylldocs/_local.yml
Labels: P1

#4003 modify perf trace logging
  packages/composer-runtime-hlfv1/lib/composer.js
  packages/composer-runtime-hlfv1/lib/nodedatacollection.js
  packages/composer-runtime-hlfv1/lib/nodedataservice.js
  packages/composer-runtime-hlfv1/lib/nodeutils.js
  packages/composer-runtime/lib/accesscontroller.js
  packages/composer-runtime/lib/engine.queries.js
  packages/composer-runtime/lib/engine.registries.js
  packages/composer-runtime/lib/engine.resources.js
  packages/composer-runtime/lib/engine.transactions.js
Labels: Next Build To Merge

#3906 Adding routes for login sections (Issue 2860)
  packages/composer-playground/e2e/component/create-business-network-card.ts
  packages/composer-playground/e2e/component/deploy.ts
  packages/composer-playground/e2e/component/login.ts
  packages/composer-playground/e2e/constants.ts
  packages/composer-playground/e2e/specs/login.spec.ts
  packages/composer-playground/protractor.web.conf.js
  packages/composer-playground/src/app/app.component.spec.ts
  packages/composer-playground/src/app/app.component.ts
  packages/composer-playground/src/app/login/login.component.html
  packages/composer-playground/src/app/login/login.component.spec.ts
  packages/composer-playground/src/app/login/login.component.ts
Labels: Next Build To Merge

#4013 Added 1 line warning not to use sudo
  packages/composer-website/jekylldocs/installing/development-tools.md
Labels: Next Build To Merge

#4022 Move to official grpc fix
  packages/composer-connector-hlfv1/package.json
Labels: Next Build To Merge

#4033 Playground support for connection delegation
  packages/composer-common/lib/connectionprofilemanager.js
  packages/composer-common/test/connectionprofilemanager.js
  packages/composer-connector-embedded/lib/embeddedconnectionmanager.js
  packages/composer-connector-embedded/test/embeddedconnectionmanager.js
  packages/composer-playground/src/app/services/admin.service.ts
  packages/composer-tests-integration/features/cli-cards.feature
  packages/composer-tests-integration/scripts/run-integration-tests.sh
Labels: Next Build To Merge

#4081 Correct the timestamp of the log file to today
  packages/composer-common/lib/log/logger.js
Labels: Next Build To Merge

#4075 prevent double ACL checking on transaction submission
  packages/composer-runtime/lib/engine.transactions.js
  packages/composer-runtime/lib/registry.js
  packages/composer-runtime/test/engine.transactions.js
  packages/composer-runtime/test/registry.js
Labels: Next Build To Merge, P1

#4065 change references to public key, acl property ref
  packages/composer-common/test/connectionmanager.js
  packages/composer-connector-proxy/test/proxyconnectionmanager.js
  packages/composer-connector-server/test/connectorserver.js
  packages/composer-website/jekylldocs/managing/id-cards-playground.md
  packages/composer-website/jekylldocs/reference/acl_language.md
Labels: Next Build To Merge, P1

#4035 Check for and handle listen errors (resolves #4029)
  packages/composer-connector-server/lib/connectorserver.js
  packages/composer-connector-server/test/connectorserver.js
  packages/composer-playground-api/cli.js
  packages/composer-playground-api/index.js
  packages/composer-playground-api/package.json
  packages/composer-playground-api/routes/npm.js
  packages/composer-playground-api/test/index.js
  packages/composer-playground/cli.js
  packages/composer-playground/index.js
Labels: Next Build To Merge, P1

#4090 manual version bump
  lerna.json
  package.json
  packages/composer-admin/package.json
  packages/composer-cli/package.json
  packages/composer-client/package.json
  packages/composer-common/package.json
  packages/composer-connector-embedded/package.json
  packages/composer-connector-hlfv1/package.json
  packages/composer-connector-proxy/package.json
  packages/composer-connector-server/package.json
  packages/composer-connector-web/package.json
  packages/composer-cucumber-steps/package.json
  packages/composer-documentation/package.json
  packages/composer-playground-api/package.json
  packages/composer-playground/package.json
  packages/composer-report/package.json
  packages/composer-rest-server/package.json
  packages/composer-runtime-embedded/package.json
  packages/composer-runtime-hlfv1/package.json
  packages/composer-runtime-pouchdb/package.json
  packages/composer-runtime-web/package.json
  packages/composer-runtime/package.json
  packages/composer-tests-functional/package.json
  packages/composer-tests-integration/package.json
  packages/composer-wallet-filesystem/package.json
  packages/composer-wallet-inmemory/package.json
  packages/composer-website/package.json
  packages/generator-hyperledger-composer/package.json
  packages/loopback-connector-composer/package.json
Labels: Next Build To Merge
