Repository hyperledger/composer, pull requests merged in 2018-03, with the labels that each got.

#3447 New Google OAUTH2.0 authentication for REST server tutorial
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/auth_diagram.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/authorization-error.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/deploy-network.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/download-bna.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/get-historian-listing.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/get-historian.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/get-trader-resp.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/get-wallet.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/client-keys.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/create_client_id.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/credentials-service.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/credentials_svc_acc.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/download-service-creds.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/google_apis.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/product-name.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/project.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google/setup_credentials.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/google_auth.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/import-jdoe-wallet.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/import-kcoe-wallet.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/rest-server-launch.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/rest-server-token.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/set-default-kcoe.png
  packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md
Labels: docs, tutorials

#3560 fix rest server by backing out importCard change
  packages/composer-admin/lib/adminconnection.js
  packages/composer-admin/test/adminconnection.js
Labels: P1

#3564 upgrade to node-sdk 1.0.5
  packages/composer-connector-hlfv1/package.json
Labels: P1, v0.16.x

#3629 Add overview OAUTH2.0 diagram, add corrections in doc
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/auth_diagram.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/import-jdoe-wallet.png
  packages/composer-website/jekylldocs/assets/img/tutorials/auth/intro_diagram.png
  packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md
Labels: docs, tutorials

#3668 update to API docs in prep for Namespaces
  packages/composer-website/apigen-opus/_template/class.njk
  packages/composer-website/jekylldocs/assets/css/grid-layout.min.css
  packages/composer-website/jekylldocs/assets/css/grid-layout.scss
  packages/composer-website/scripts/api-doc-index.md.tpl
Labels: design, docs

#3626 Add Angular Generator documentation to Developer tutorial
  packages/composer-website/jekylldocs/tutorials/developer-tutorial.md
Labels: P2

#3671 Add version editor to playground
  packages/composer-playground/e2e/component/editor.ts
  packages/composer-playground/e2e/constants.ts
  packages/composer-playground/e2e/specs/editor-define.spec.ts
  packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
  packages/composer-playground/src/app/editor/add-file/add-file.component.spec.ts
  packages/composer-playground/src/app/editor/editor-file/editor-file.component.scss
  packages/composer-playground/src/app/editor/editor-file/editor-file.component.spec.ts
  packages/composer-playground/src/app/editor/editor-file/editor-file.component.ts
  packages/composer-playground/src/app/editor/editor.component.html
  packages/composer-playground/src/app/editor/editor.component.scss
  packages/composer-playground/src/app/editor/editor.component.spec.ts
  packages/composer-playground/src/app/editor/editor.component.ts
  packages/composer-playground/src/app/services/client.service.spec.ts
  packages/composer-playground/src/app/services/client.service.ts
  packages/composer-playground/src/app/services/editor-file.spec.ts
  packages/composer-playground/src/app/services/editor-file.ts
  packages/composer-playground/src/app/services/file.service.spec.ts
  packages/composer-playground/src/app/services/file.service.ts
  packages/composer-playground/src/app/test/test.component.html
  packages/composer-playground/src/app/test/test.component.scss
  packages/composer-playground/src/assets/styles/base/_typography.scss
  packages/composer-website/jekylldocs/playground/playground-index.md
Labels: P1

#3665 Identity warn when bound participant not found (Issue 3011)
  package.json
  packages/composer-cli/lib/cmds/identity/lib/list.js
  packages/composer-cli/test/identity/list.js
  packages/composer-playground-api/basic-sample-network-0.1.9.tgz
  packages/composer-playground-api/basic-sample-network-0.2.2.tgz
  packages/composer-playground-api/routes/npm.js
  packages/composer-playground/e2e/component/deploy.ts
  packages/composer-playground/e2e/component/editor.ts
  packages/composer-playground/e2e/component/identity-issued.ts
  packages/composer-playground/e2e/component/identity.ts
  packages/composer-playground/e2e/component/issue-identity.ts
  packages/composer-playground/e2e/component/test.ts
  packages/composer-playground/e2e/constants.ts
  packages/composer-playground/e2e/data/files/identity/participants/CONGA
  packages/composer-playground/e2e/data/sample-networks/import-network/permissions.acl
  packages/composer-playground/e2e/scripts/cleanTestFolders.sh
  packages/composer-playground/e2e/specs/identity.spec.ts
  packages/composer-playground/e2e/tmp/.gitignore
  packages/composer-playground/e2e/utils/operations-helper.ts
  packages/composer-playground/protractor.fabric.conf.js
  packages/composer-playground/protractor.web.conf.js
  packages/composer-playground/src/app/identity/identity.component.html
  packages/composer-playground/src/app/identity/identity.component.spec.ts
  packages/composer-playground/src/app/identity/identity.component.ts
  packages/composer-playground/src/app/identity/issue-identity/issue-identity.component.html
  packages/composer-playground/src/app/identity/issue-identity/issue-identity.component.spec.ts
  packages/composer-playground/src/app/identity/issue-identity/issue-identity.component.ts
  packages/composer-playground/src/app/test/registry/registry.component.html
  packages/composer-tests-integration/features/cli-identities.feature
Labels: P1

#3675 Final logging updates
  packages/composer-cli/lib/cmds/network/lib/loglevel.js
  packages/composer-cli/lib/cmds/network/loglevelCommand.js
  packages/composer-cli/test/network/loglevel.js
  packages/composer-common/lib/log/consolelogger.js
  packages/composer-common/lib/log/logger.js
  packages/composer-common/lib/log/node.js
  packages/composer-common/lib/log/tree.js
  packages/composer-common/lib/log/winstonInjector.js
  packages/composer-common/test/log/consolelogger.js
  packages/composer-common/test/log/logger.js
  packages/composer-common/test/log/tree.js
  packages/composer-connector-server/cli.js
  packages/composer-connector-server/test/connectorserver.js
  packages/composer-playground-api/cli.js
  packages/composer-playground/cli.js
  packages/composer-playground/src/app/services/admin.service.ts
  packages/composer-playground/src/app/services/identity-card.service.ts
  packages/composer-runtime-embedded/lib/embeddedloggingservice.js
  packages/composer-runtime-embedded/test/embeddedloggingservice.js
  packages/composer-runtime-hlfv1/lib/nodedatacollection.js
  packages/composer-runtime-hlfv1/lib/nodedataservice.js
  packages/composer-runtime-hlfv1/lib/nodehttpservice.js
  packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
  packages/composer-runtime-hlfv1/test/nodeloggingservice.js
  packages/composer-runtime-web/lib/webloggingservice.js
  packages/composer-runtime-web/test/webloggingservice.js
  packages/composer-runtime/lib/engine.js
  packages/composer-runtime/lib/engine.logging.js
  packages/composer-runtime/lib/loggingservice.js
  packages/composer-runtime/lib/networkmanager.js
  packages/composer-runtime/test/engine.js
  packages/composer-runtime/test/engine.logging.js
  packages/composer-runtime/test/loggingservice.js
  packages/composer-runtime/test/networkmanager.js
  packages/composer-tests-integration/features/cli-network.feature
Labels: P1

#3693 Fix version of tar that composer report cli command requires
  packages/composer-cli/package.json
  packages/composer-playground-api/package.json
  packages/composer-report/package.json
Labels: P1

#3686 Issue 3684 update build scripts for v0.19
  .travis/base.sh
  .travis/deploy.sh
  .travis/script.sh
  packages/composer-website/jekylldocs/_v0.16-unstable.yml
  packages/composer-website/jekylldocs/_v0.16.yml
  packages/composer-website/package.json
  packages/composer-website/scripts/linkcheck.sh
Labels: P1

#3691 Angular Changes
  packages/composer-tests-integration/scripts/config.yaml
  packages/generator-hyperledger-composer/generators/angular/index.js
  packages/generator-hyperledger-composer/generators/angular/templates/e2e/app.e2e-spec.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/Transaction/Transaction.component.css
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/Transaction/Transaction.component.html
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/Transaction/Transaction.component.spec.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/Transaction/Transaction.component.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/Transaction/Transaction.service.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/app-routing.module.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/app.component.css
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/app.component.html
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/app.module.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.html
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.css
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.html
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.spec.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.service.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.component.css
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.component.html
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.component.spec.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.component.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.service.ts
  packages/generator-hyperledger-composer/generators/angular/templates/src/main.ts
  packages/generator-hyperledger-composer/generators/util.js
  packages/generator-hyperledger-composer/package.json
  packages/generator-hyperledger-composer/test/angular-archive.js
  packages/generator-hyperledger-composer/test/angular-network.js
Labels: P1

#3694 Fix for query with multiple AND conditions
  packages/composer-runtime/lib/querycompiler.js
  packages/composer-runtime/test/querycompiler.js
  packages/composer-tests-integration/features/queries.feature
  packages/composer-tests-integration/resources/sample-networks/queries-network/queries.qry
Labels: P1

#3698 Add upgrade dialog to playground
  packages/composer-playground/e2e/component/upgrade.ts
  packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
  packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.html
  packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.spec.ts
  packages/composer-playground/src/app/editor/editor.component.spec.ts
  packages/composer-playground/src/app/editor/editor.component.ts
  packages/composer-playground/src/app/editor/editor.module.ts
  packages/composer-playground/src/app/editor/upgrade/index.ts
  packages/composer-playground/src/app/editor/upgrade/upgrade.component.html
  packages/composer-playground/src/app/editor/upgrade/upgrade.component.scss
  packages/composer-playground/src/app/editor/upgrade/upgrade.component.spec.ts
  packages/composer-playground/src/app/editor/upgrade/upgrade.component.ts
  packages/composer-playground/src/assets/styles/components/_dropdown.scss
Labels: P1
