Repository hyperledger/composer, pull requests merged in 2018-09, with the labels that each got.

#4399 [master] update npm dependencies
  packages/composer-common/lib/factory.js
  packages/composer-common/package.json
  packages/composer-connector-hlfv1/package.json
  packages/composer-connector-proxy/package.json
  packages/composer-documentation/lib/processors/visitors/info.js
  packages/composer-documentation/package.json
  packages/composer-playground-api/package.json
  packages/composer-playground/package.json
  packages/composer-rest-server/package.json
  packages/composer-runtime-embedded/package.json
  packages/composer-runtime-pouchdb/package.json
  packages/composer-runtime/package.json
Labels: Next Build To Merge

#4402 Updated 2 commands in Tutorial
  packages/composer-website/jekylldocs/tutorials/invoke-composer-network.md
Labels: Next Build To Merge, P1

#4313 [Master] dynamic logging, ability to disable explorer
  packages/composer-rest-server/cli.js
  packages/composer-rest-server/lib/util.js
  packages/composer-rest-server/server/boot/composer-discovery.js
  packages/composer-rest-server/server/boot/root.js
  packages/composer-rest-server/server/composer.json
  packages/composer-rest-server/server/server.js
  packages/composer-rest-server/server/servercmd.js
  packages/composer-rest-server/test/cli.js
  packages/composer-rest-server/test/lib/util.js
  packages/composer-rest-server/test/root.js
  packages/composer-rest-server/test/server/server.js
  packages/composer-rest-server/test/server/servercmd.js
  packages/composer-rest-server/test/system.js
  packages/composer-website/jekylldocs/integrating/getting-started-rest-api.md
  packages/loopback-connector-composer/lib/businessnetworkconnector.js
  packages/loopback-connector-composer/test/businessnetworkconnector.js
Labels: Next Build To Merge, P1

#4413 Version Bump tp 0.20.2
  lerna.json
  package.json
  packages/composer-admin/package.json
  packages/composer-cli/package.json
  packages/composer-client/package.json
  packages/composer-common/package.json
  packages/composer-connector-embedded/package.json
  packages/composer-connector-hlfv1/package.json
  packages/composer-connector-proxy/package.json
  packages/composer-connector-server/package.json
  packages/composer-connector-web/package.json
  packages/composer-cucumber-steps/package.json
  packages/composer-documentation/package.json
  packages/composer-playground-api/package.json
  packages/composer-playground/package.json
  packages/composer-report/package.json
  packages/composer-rest-server/package.json
  packages/composer-runtime-embedded/package.json
  packages/composer-runtime-hlfv1/package.json
  packages/composer-runtime-pouchdb/package.json
  packages/composer-runtime-web/package.json
  packages/composer-runtime/package.json
  packages/composer-tests-functional/package.json
  packages/composer-tests-integration/package.json
  packages/composer-wallet-filesystem/package.json
  packages/composer-wallet-inmemory/package.json
  packages/composer-website/package.json
  packages/generator-hyperledger-composer/package.json
  packages/loopback-connector-composer/package.json
Labels: Next Build To Merge, P1

#4415 [0.19.x] Improvements to connector logging and disconnection
  packages/composer-common/lib/factory.js
  packages/composer-common/lib/log/logger.js
  packages/composer-connector-hlfv1/lib/hlfconnection.js
  packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
  packages/composer-connector-hlfv1/test/hlfconnection.js
  packages/composer-rest-server/test/system.js
  packages/composer-runtime/test/networkmanager.js
Labels: P1
