Repository hyperledger/composer, pull requests merged in 2018-10, with the labels that each got.

#4433 [0.19.x] query should try other peers
  packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
  packages/composer-connector-hlfv1/test/hlfqueryhandler.js
Labels: Next Build To Merge, P1

#4429 [0.19.x] Fix logging for runtime, set default to warning
  packages/composer-common/lib/connectionprofilemanager.js
  packages/composer-runtime-hlfv1/lib/composer.js
  packages/composer-runtime-hlfv1/lib/nodedatacollection.js
  packages/composer-runtime-hlfv1/lib/nodedataservice.js
  packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
  packages/composer-runtime-hlfv1/lib/nodeutils.js
  packages/composer-runtime-hlfv1/test/nodeloggingservice.js
  packages/composer-runtime/lib/accesscontroller.js
  packages/composer-runtime/lib/engine.queries.js
  packages/composer-runtime/lib/engine.registries.js
  packages/composer-runtime/lib/engine.resources.js
  packages/composer-runtime/lib/engine.transactions.js
Labels: P1

#4431 [0.19.x] remove references to LIMIT and SKIP
  packages/composer-website/jekylldocs/business-network/query.md
  packages/composer-website/jekylldocs/reference/query-language.md
Labels: P1

#4420 [Master] Clarify when events are emitted in the docs
  packages/composer-website/jekylldocs/business-network/publishing-events.md
Labels: P3

#4491 [0.19.x] Fix Broken Dependency in Rest Server
  packages/composer-rest-server/package.json
Labels: Next Build To Merge, P1

#4490 [Master] Fix broken dependency in Rest Server
  packages/composer-rest-server/package.json
Labels: Next Build To Merge, P1

#4486 [0.19.x] Upgrade shim to 1.1.4
  packages/composer-runtime-hlfv1/package.json
Labels: P1

#4487 [Master] Upgrade shim to 1.2.3
  packages/composer-runtime-hlfv1/package.json
Labels: P1

#4494 [0.19.x] Version bump to 0.19.18
  lerna.json
  package.json
  packages/composer-admin/package.json
  packages/composer-cli/package.json
  packages/composer-client/package.json
  packages/composer-common/package.json
  packages/composer-connector-embedded/package.json
  packages/composer-connector-hlfv1/package.json
  packages/composer-connector-proxy/package.json
  packages/composer-connector-server/package.json
  packages/composer-connector-web/package.json
  packages/composer-cucumber-steps/package.json
  packages/composer-documentation/package.json
  packages/composer-playground-api/package.json
  packages/composer-playground/package.json
  packages/composer-report/package.json
  packages/composer-rest-server/package.json
  packages/composer-runtime-embedded/package.json
  packages/composer-runtime-hlfv1/package.json
  packages/composer-runtime-pouchdb/package.json
  packages/composer-runtime-web/package.json
  packages/composer-runtime/package.json
  packages/composer-tests-functional/package.json
  packages/composer-tests-integration/package.json
  packages/composer-wallet-filesystem/package.json
  packages/composer-wallet-inmemory/package.json
  packages/composer-website/package.json
  packages/generator-hyperledger-composer/package.json
  packages/loopback-connector-composer/package.json
Labels: P1

#4496 [Master] Version Bump to 0.20.4
  lerna.json
  package.json
  packages/composer-admin/package.json
  packages/composer-cli/package.json
  packages/composer-client/package.json
  packages/composer-common/package.json
  packages/composer-connector-embedded/package.json
  packages/composer-connector-hlfv1/package.json
  packages/composer-connector-proxy/package.json
  packages/composer-connector-server/package.json
  packages/composer-connector-web/package.json
  packages/composer-cucumber-steps/package.json
  packages/composer-documentation/package.json
  packages/composer-playground-api/package.json
  packages/composer-playground/package.json
  packages/composer-report/package.json
  packages/composer-rest-server/package.json
  packages/composer-runtime-embedded/package.json
  packages/composer-runtime-hlfv1/package.json
  packages/composer-runtime-pouchdb/package.json
  packages/composer-runtime-web/package.json
  packages/composer-runtime/package.json
  packages/composer-tests-functional/package.json
  packages/composer-tests-integration/package.json
  packages/composer-wallet-filesystem/package.json
  packages/composer-wallet-inmemory/package.json
  packages/composer-website/package.json
  packages/generator-hyperledger-composer/package.json
  packages/loopback-connector-composer/package.json
Labels: P1

#4483 [0.19.x] Highlight the danger of network reset
  packages/composer-admin/lib/adminconnection.js
  packages/composer-website/jekylldocs/reference/composer.network.reset.md
Labels: P1

#4497 [0.19.x] Backport perf logging improvements
  packages/composer-common/lib/log/logger.js
  packages/composer-common/lib/log/winstonInjector.js
  packages/composer-common/test/log/logger.js
  packages/composer-connector-hlfv1/lib/hlfconnection.js
  packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
  packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
  packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
  packages/composer-connector-hlfv1/test/hlfconnection.js
  packages/composer-connector-hlfv1/test/hlfqueryhandler.js
Labels: P1

#4502 [Master] fix prereqs script
  packages/composer-website/jekylldocs/prereqs-ubuntu.sh
Labels: P1

#4503 [0.19.x] fix prereqs script
  packages/composer-website/jekylldocs/prereqs-ubuntu.sh
Labels: P1

#4499 [0.19.x] Allow txid to be passed to query requests
  packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
  packages/composer-connector-hlfv1/test/hlfqueryhandler.js
Labels: P1

#4500 [Master] Allow txid to be passed to query requests
  packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
  packages/composer-connector-hlfv1/test/hlfqueryhandler.js
Labels: P1
